version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./SibersProjectWeb/
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=db;Initial Catalog=sibers_db;User Id=sa;Password=qwerty;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "qwerty"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: {}